### ISSUE TITLE
Gauntlet results (v1.1.3) and some interesting position

### ISSUE THREAD

**Issue by tissatussa** [Timmoth/Sapling#13]
I let the new version v1.1.3 play some games against 28 strong engines, a Gauntlet "by hand", 5m3s from starting position. I thought Sapling is 3100 but the results show it's much stronger ..
pgn ZIP here : [sapling-v1.1.3-vs-strong-engines.zip](https://github.com/user-attachments/files/17181487/sapling-v1.1.3-vs-strong-engines.zip)

![pgn-list-240929](https://github.com/user-attachments/assets/599e268b-7362-4fb7-9429-ba16971090e3)

[ sorted list in SCID ]

One game had a spectacular ending : Sapling made a draw against the new 'Priessnitz', see https://github.com/kfeske/Priessnitz - rating unknow .. eval dropped in this position :

![Priessnitz-position-eval-bar-by-SF17](https://github.com/user-attachments/assets/0ab7755c-ab44-49ab-b13d-cbef8ce51c46)

[ eval bar by SF 17 ]

this type of position could have occured in any game, it holds some "horizon effect" : the move Bxh7+ is admired for a long time, it's considered bestmove upto a certain depth, then engines prefer Qe4. Stockfish instantly finds Qe4 bestmove and sticks to it, but Bxh7 is considered "also good" for a long time .. finally Bxh7 is only 0.00

SF 17 MultiPV 5 :

![SF-v17-NNUE-mpv-5-Priessnitz-position](https://github.com/user-attachments/assets/f9938ef9-11d8-4582-81fd-7feeb04a609b)

Sapling v1.1.3 :

![Sapling-v1 1 3-NNUE-mpv-1-Priessnitz-position](https://github.com/user-attachments/assets/67287e47-e5ec-4f32-a4a6-e32478de05ad)

in that 5m3s game Sapling played Bxh7 ..

**Comment by Timmoth** [comment]
>  I thought Sapling is 3100 but the results show it's much stronger .. 

This is extremely promising to see! Those results are crazy! Hopefully once I've got the tuning done and Corrhist implemented and another round of datagen it'll start competing with some of the top engines.

It's an interesting position, you're running on two threads right? It might be that it does find Qe4 earlier but the thread voting prefers Bxh7 until later on. I'll give this a look because it might uncover an issue with how multithreaded searches decide on the best move.

**Comment by tissatussa** [comment]
> This is extremely promising to see! Those results are crazy!

that's what i think also .. but don't take it all too serious, these ratings are an indication, although i took them from the (latest) CCRL list and they should be up-to-date (but they fluctuate) .. next time we let Sapling play against a same engine another result may come .. a coming tournament, like the TalkChess forum guy (from the other recent Issue) is organising, will disclose more ..

what is Corrhist ? can you elaborate on this ? this term i often see with other engine developers .. 'hist' must stand for 'history', but 'Corr' ?

> it'll start competing with some of the top engines

it surely will !
i sorted the games by opponent rating : Patricia (! i told about her in another Issue) is the first engine defeating yours .. btw. i just picked a few strong engines from my archive, nowadays many others exist which are about equal in strength, also non-NN's ..

> ..you're running on two threads right?

yes, but no more, my notebook has its limits :

```
          `-/osyhddddhyso/-`              roelof@roelof-HP-Elite-x2-1012-G2 
        .+yddddddddddddddddddy+.           --------------------------------- 
      :yddddddddddddddddddddddddy:         OS: Xubuntu 22.04.4 LTS x86_64 
    -yddddddddddddddddddddhdddddddy-       Host: HP Elite x2 1012 G2 
   odddddddddddyshdddddddh`dddd+ydddo      Kernel: 5.15.0-107-generic 
 `yddddddhshdd-   ydddddd+`ddh.:dddddy`    Uptime: 5 hours, 54 mins 
 sddddddy   /d.   :dddddd-:dy`-ddddddds    Packages: 3955 (dpkg), 19 (snap) 
:ddddddds    /+   .dddddd`yy`:ddddddddd:   Shell: bash 5.1.16 
sdddddddd`    .    .-:/+ssdyodddddddddds   Resolution: 1920x1080, 1920x1080 
ddddddddy                  `:ohddddddddd   DE: Xfce 4.16 
dddddddd.                      +dddddddd   WM: Xfwm4 
sddddddy                        ydddddds   WM Theme: Default 
:dddddd+                      .oddddddd:   Theme: Adwaita-dark [GTK2/3] 
 sdddddo                   ./ydddddddds    Icons: elementary-xfce-darker [GTK2/3] 
 `yddddd.              `:ohddddddddddy`    Terminal: xfce4-terminal 
   oddddh/`      `.:+shdddddddddddddo      Terminal Font: DejaVu Sans Mono 9 
    -ydddddhyssyhdddddddddddddddddy-       CPU: Intel i5-7200U (4) @ 3.100GHz 
      :yddddddddddddddddddddddddy:         GPU: Intel HD Graphics 620 
        .+yddddddddddddddddddy+.           Memory: 6249MiB / 7816MiB 
           `-/osyhddddhyso/-`
```

> ..It might be that it does find Qe4 earlier but the thread voting prefers Bxh7 until later on..

what is 'the thread voting' ? i think i understand how engines search and what happens then (recursively), but not combined with threads .. did you ever consider implementing MultiPV ? I like to use that for analyses, not in CuteChess : it's discouraged, they say mpv-1 just gives the best results, although CuteChess shows that UCI option and we can set it for games .. i once tried to set it, but then CuteChess is not able to properly display all mpv lines, its output becomes confusing, and it's not clear MultiPV can improve bestmoves .. however, for a programmer MultiPV can help during development, it has several practical advantages, for both coder and user .. i encourage you to implement this technique, you'll learn a lot (it seems not easy to create a smooth MultiPV mechanism) and you'll be invited to compose & feed special test positions to see how the engine handles them - and why !? But i always wonder : doesn't the engine do kind of MultiPV anyhow ? I mean, moves are rejected for another bestmove constantly, so in fact a top[#]list exists ?

> ..it might uncover an issue with how multithreaded searches decide on the best move

can you provide a bit more info on this ? Maybe by describing what you mean, i have some noob question which makes you think out-of-the-box .. [a little story: many years ago my brother started coding Pascal, he created a file manager for DOS and i helped him, i knew about lists, arrays, sorting, etc.] .. i never looked into his code, believe me, i only tested his next version and described what happened and what i expected to happen]

**Comment by Timmoth** [comment]
> what is Corrhist ? can you elaborate on this ? this term i often see with other engine developers .. 'hist' must stand for 'history', but 'Corr' ?

I've actually just implemented 'pawn correction history' in the latest release v1.1.5, it should make the engine much stronger in long time control.

The idea is that you keep track of how your static evaluation differs from the actual eval and then adjust future static evaluations for similar positions. So for instance if I calculate a low static evaluation for a position with pawns in a specific layout the next time I see that same layout I may reduce the static evaluation to bring it more inline. 

>i sorted the games by opponent rating : Patricia (! i told about her in another Issue) is the first engine defeating yours

It's fairing OK against Patricia at the moment - they're both in the same CCRL division right now! 
https://ccrl.live/16064/result-table

>what is 'the thread voting' ?

The idea is that when you run multiple threads you run multiple independent searches, the only thing they share is the transposition table which stores some info on positions it's seen before. Because you're performing multiple separate searches you will get multiple separate results, and thread voting allows your searches to agree on which PV is the best. 

>can you provide a bit more info on this ? Maybe by describing what you mean

Well it's possible that the algorithm for threads voting on the best PV is not working optimally, and it may be choosing a sub optimal PV. I haven't spent too much time perfecting it, but I should experiment with this.
